### ISSUE TITLE
Always Unauthorized when testing the sample

### ISSUE THREAD

**Issue by woodwind** [AzureADSamples/NativeClient-WindowsStore#18]
I use the sample and follow the steps, but I cannot login to the app whenever I use normal account or admin
I track the steps and find the statuscode of response is "Unauthorized" though I can login to AD successfully.

I am sure that I have followed the document. So what is the issue?

**Comment by dstrockis** [comment]
Hey @woodwind... Is that the status code from the request to the To-Do list service?  If so, it is most likely something to do with your configuration values on the To-Do list service.

**Comment by woodwind** [comment]
I guess that too because the request is sent to the service. However I just follow the steps to configure values. I don't understand why there is such permission issue.

**Comment by dstrockis** [comment]
If you post the code from your TodoListService Startup.Auth.cs file, as well as the token sent in the Authorization header of the request, I can have a look for you.

**Comment by woodwind** [comment]
Ah...I find an issue in ida:audience, while after I change it, the authentication page is missing now and it prompts error for Access Denied. I think I need to check the steps and the project again. I will close the issue, thx!

**Comment by dstrockis** [comment]
Cool, no problem.
